### ISSUE TITLE
Campfire Games Section 

### ISSUE THREAD

**Issue by farisalipk** [bitcamp/bitcamp-site-2023#12]
### **Acceptance Criteria**

- Create an section detailing Campfire Games, according to the [mockup](https://www.figma.com/file/dGDI4sp6Cf9npVmbZGAbN5/Untitled?node-id=0%3A1&t=7N0WMS3Y0u58eDIz-0)
- Component is dynamic, with input consisting of team name, description, and image. The header color should be set according to the team name, and applied styles should be readable and simple. (If you think hardcoding the colors is more efficient then go for it)
- Responsive, test with various screen sizes and verify behavior is as expected : allow for vertical stacking at appropriate screen widths
- Linted and formatted

### **References**
<img width="743" alt="image" src="https://user-images.githubusercontent.com/81818189/220229196-7fa344a0-a156-4ca9-b13a-b012d486f64c.png">

**Comment by jasoneliu** [comment]
Closed by #45
