### ISSUE TITLE
Footer Image

### ISSUE THREAD

**Issue by farisalipk** [bitcamp/bitcamp-site-2023#32]
### **Acceptance Criteria**

- Create a component for the footer image, according to the [mockup](https://www.figma.com/file/dGDI4sp6Cf9npVmbZGAbN5/Untitled?node-id=0%3A1&t=7N0WMS3Y0u58eDIz-0)
- Applied styles should be readable and simple.
- Responsive, test with various screen sizes and verify behavior is as expected :
- Linted and formatted

### **References**
<img width="387" alt="image" src="https://user-images.githubusercontent.com/81818189/220230618-aa8a4b69-94b2-4dcc-b545-548015da4e0a.png">

**Comment by jasoneliu** [comment]
Resolved by [e699a8f](https://github.com/bitcamp/bitcamp-site-2023/commit/e699a8ffff5c0eeb76df43baac6494026a371b4c)
